repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: local
    hooks:
      - id: no-symlinks
        name: no symlinks
        description: "Check for symlinks"
        entry: "symlinks may not be committed due to platform support"
        language: fail
        types: [symlink]

  - repo: https://github.com/google/yapf
    rev: v0.40.1
    hooks:
      - id: yapf

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.285
    hooks:
      - id: ruff

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.323
    hooks:
    - id: pyright
