name: Check typing

on:
  push:

jobs:
  check_typing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: pdm-project/setup-pdm@v3
      with:
        python-version: "3.10"
        cache: true

    - run: pdm install -Gtype-check
    - run: cp rpgcord/config.example.py rpgcord/config.py
    - run: pdm run pyright
